package mainpackage;

public class Lexer {

	public static String[][] lexer = {
			{"comment",				"^(#.*)"},
			{"dp",					"^:"},
			{"op",					""},
			{"cp",					""},
			{"pc",					""},
			{"br",					"^\\s*\\+\\s*\\n\\s*"},
			{"nl",					"^\n"},
			{"coma",				"^,"},
			{"tab",					"^(\\s{4})"},
			{"s",					"\\s{1}"},
			{"measure",				"^((px)|(%))"},
			{"meta",				"^((author)|(keywords)|(lang)|(redirect)|(pageicon)|(title)|(charset)|(description))"},
			{"import",				"^import"},
			{"define",				"^define"},
			{"include",				"^include"},
			{"type",				"^type"},
			{"name",				"^name"},
			{"content",				"^content"},
			{"container",			"^((box)|(vbox)|(hbox)|(sidebox)|(modalbox))"},
			{"itemcont",			"^((tablebox)|(dropdownbox)|(tabbedbox)|(accordionbox)|(slideshow))"},
			{"radiogroup",			"^radiogroup"},
			{"radiobutton",			"^radiobutton"},
			{"component",			"^((button)|(image)|(video)|(audio)|(textfield)|(checkbox)|(label)|(progressbar))"},
			{"item",				"^item"},
			{"attr",				"^((alt)|(poster)|(src)|(autoplay)|(controls)|(loop)|(muted)|(preload)|(onclick)|(onchange)|(alignment)|(type)|(placeholder)|(header)|(text-align)|(text-decoration)|(text-color)|(text)|(font-size)|(font-family)|(animation)|(background-color)|(border-color)|(border-radius)|(border-size)|(border)|(class)|(effect)|(elevation)|(height)|(id)|(link)|(margin)|(padding)|(slots)|(tooltip)|(width)|(closable)|(delay)|(slide-controls)|(indicators)|(caption-position)|(caption))"},
			{"bool",				"^((true)|(false))"},
			{"color",				"^((red)|(pink)|(purple)|(deep-purple)|(indigo)|(blue-gray)|(blue)|(light-blue)|(cyan)|(aqua)|(teal)|(green)|(light-green)|(lime)|(sand)|(khaki)|(yellow)|(amber)|(orange)|(deep-orange)|(brown)|(light-gray)|(gray)|(dark-gray)|(pale-red)|(pale-yellow)|(pale-green)|(pale-blue))"},
			{"font",				"^((TimesNewRoman)|(Georgia)|(AndaleMono)|(ArialBlack)|(Arial)|(Impact)|(TrebuchetMS)|(Verdana)|(ComicSansMS)|(CourierNew))"},
			{"tdecor",				"^((wide)|(bold)|(italic)|(shadowed)|(underlined)|(strikethrough))"},
			{"align",				"^((top-right)|(top-left)|(bottom-right)|(bottom-left)|(center)|(top)|(bottom)|(right)|(left))"},
			{"effect",				"^((opacity-max)|(opacity-min)|(opacity)|(grayscale-max)|(grayscale-min)|(grayscale)|(sepia-max)|(sepia-min)|(sepia))"},
			{"animation",			"^((zoom)|(fading)|(spin)|(move-up)|(move-down)|(move-right)|(move-left))"},
			{"charset",				"^((cs-8859)|(cs-ansi)|(cs-ascii)|(cs-utf-8))"},	
			{"text",				"^((\\\"[^\"]*\\\")|('[^']*'))"},
			{"integer",				"^(0|([1-9][0-9]*))"},
			{"real",				"^((0.[0-9]*[1-9])|([1-9][0-9]*.[0-9]*[1-9]))"},
			{"definetype",			"^((color)|(font)|(tag)|(attr))"},
			{"indicators",	 		"^((dots)|(numbers)|(miniatures))"},
			{"slide-controls",		"^((angulars-bottom)|(angulars)|(arrows-bottom)|(arrows))"},
			{"none",				"^none"}};
}